### ISSUE TITLE
Packages for OS X / macOS

### ISSUE THREAD

**Issue by Crissov** [vXBaKeRXv/vxbakerxv.github.io#1]
I know this is just supposed to be hosting your Cydia packages, but could you please also provide the bare font files somewhere so people can install them manually on their Macs?

**Comment by vXBaKeRXv** [comment]
I started to go with iOS emoji layout. They use PUA and only 3 set sizes. 
  Package limit on here is 60mb and to get around it looks to complex for me.  Latest mac now uses 9 ppem-set sizes in the sbix. 

No point in adding other extras like hand shake and wrestlers skin tones ect because the system needs modified-updated to handle them.  Samsungs notos extra symbols will not work either due to same reasons. Adding a sbix font to a app with a custom font family name, might work out for those...
 So these are not fully complete.

**Comment by d4mation** [comment]
I was able to unpackage the `.deb` file and grab the font file that way. It is a `.ttf` file buried in there. Works just fine.

![image](https://user-images.githubusercontent.com/7770631/35934317-34b23542-0c0b-11e8-81f3-74857174e5a8.png)

**Comment by vXBaKeRXv** [comment]
The defualt Mac apple emoji TTC contains 2 TTF fonts inside and has 9 set sizes for scaling. To keep them small and true to iOS, those within only use 3 set sizes. Falling back on a single TTF when the system expects TTC, will work but might cause problems in some places because they are using the fontfamily name that's contained in the other font within the TTC. Githubs has a small max file size limit and to get around you need to use a complex route with a 3rd party.
